# Generated by Django 3.2.4 on 2021-06-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['s_id'], 'verbose_name': '库存清单', 'verbose_name_plural': '库存清单'},
        ),
        migrations.AlterModelTable(
            name='stock',
            table='stock',
        ),
    ]
