# Generated by Django 3.2.4 on 2021-07-02 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_goods_sp_id'),
        ('stock', '0004_alter_stock_s_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='g_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='st_goods_id', to='goods.goods', unique=True, verbose_name='商品编号'),
        ),
    ]
