# Generated by Django 3.2.4 on 2021-07-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_stock_g_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.CharField(max_length=255, null=True, verbose_name='计量单位'),
        ),
    ]
