# Generated by Django 3.2.4 on 2021-07-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_stock_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='st_id',
        ),
    ]
