# Generated by Django 3.2.4 on 2021-07-02 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_supplier_sp_id'),
        ('stock', '0008_auto_20210702_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='unit',
        ),
        migrations.AlterField(
            model_name='stock',
            name='sp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier', verbose_name='供货商编号'),
        ),
    ]
