# Generated by Django 3.2.4 on 2021-07-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20210702_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='s_num',
            field=models.PositiveIntegerField(verbose_name='库存数量'),
        ),
    ]
