# Generated by Django 3.2.4 on 2021-06-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='depart',
            field=models.CharField(choices=[('sale', '销售部门'), ('purchase', '采购部门'), ('manage', '管理部门')], max_length=255, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], max_length=255, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='job',
            field=models.CharField(max_length=255, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='st_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='员工编号'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='姓名'),
        ),
    ]
