# Generated by Django 3.2.4 on 2021-06-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20210630_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='st_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='员工编号'),
        ),
    ]
