# Generated by Django 3.2.4 on 2021-06-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_st_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='st_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='员工编号'),
        ),
    ]
