# Generated by Django 3.2.4 on 2021-06-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['p_id'], 'verbose_name': '进货清单', 'verbose_name_plural': '进货清单'},
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='purchase',
        ),
    ]
