# Generated by Django 3.2.4 on 2021-07-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_goods_g_id'),
        ('purchase', '0004_alter_purchase_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='g_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.goods', verbose_name='商品编号'),
        ),
    ]
