# Generated by Django 3.2.4 on 2021-07-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_alter_purchase_g_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='g_name',
        ),
    ]
