# Generated by Django 3.2.4 on 2021-07-01 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_goods_sp_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0003_alter_supplier_sp_id'),
        ('purchase', '0007_remove_purchase_g_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='g_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='p_goods_id', to='goods.goods', verbose_name='商品编号'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='sp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier', verbose_name='供货商编号'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='st_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='员工编号'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='p_goods_unit', to='goods.goods', verbose_name='计量单位'),
        ),
    ]
