# Generated by Django 3.2.4 on 2021-07-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_alter_purchase_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='unit',
        ),
    ]
