# Generated by Django 3.2.4 on 2021-07-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_remove_purchase_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='p_num',
            field=models.PositiveIntegerField(verbose_name='进货数量'),
        ),
    ]
