# Generated by Django 3.2.4 on 2021-06-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('g_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='商品编号')),
                ('g_name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('g_type', models.CharField(max_length=255, verbose_name='商品类型')),
                ('unit', models.CharField(max_length=255, verbose_name='计量单位')),
            ],
        ),
    ]
