# Generated by Django 3.2.4 on 2021-06-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['g_id'], 'verbose_name': '商品清单', 'verbose_name_plural': '商品清单'},
        ),
        migrations.AlterModelTable(
            name='goods',
            table='goods',
        ),
    ]
