# Generated by Django 3.2.4 on 2021-06-30 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20210630_2125'),
        ('supplier', '0002_auto_20210630_2125'),
        ('goods', '0003_auto_20210630_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='p_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.purchase', verbose_name='进货价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.supplier', verbose_name='供货商编号'),
        ),
    ]
