# Generated by Django 3.2.4 on 2021-07-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_goods_g_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='p_price',
        ),
    ]
