# Generated by Django 3.2.4 on 2021-07-01 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_supplier_sp_id'),
        ('goods', '0006_remove_goods_p_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='sp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier', verbose_name='供货商编号'),
        ),
    ]
