# Generated by Django 3.2.4 on 2021-06-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('sp_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='供货商编号')),
                ('sp_name', models.CharField(max_length=255, verbose_name='供货商名称')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('c_person', models.CharField(max_length=255, verbose_name='联系人')),
                ('c_phone', models.CharField(max_length=255, verbose_name='联系电话')),
            ],
        ),
    ]
