# Generated by Django 3.2.4 on 2021-06-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['sp_id'], 'verbose_name': '供货商', 'verbose_name_plural': '供货商'},
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='supplier',
        ),
    ]
