# Generated by Django 3.2.4 on 2021-06-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20210630_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='sp_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='供货商编号'),
        ),
    ]
