# Generated by Django 3.2.4 on 2021-06-30 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sa_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='销售编号')),
                ('s_num', models.IntegerField(verbose_name='销售数量')),
                ('s_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='销售价格')),
                ('s_time', models.DateTimeField(auto_now_add=True, verbose_name='销售时间')),
                ('g_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sa_goods_id', to='goods.goods')),
                ('g_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sa_goods_name', to='goods.goods')),
                ('sp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.supplier')),
                ('st_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sa_goods_unit', to='goods.goods')),
            ],
        ),
    ]
