# Generated by Django 3.2.4 on 2021-06-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['sa_id'], 'verbose_name': '销售清单', 'verbose_name_plural': '销售清单'},
        ),
        migrations.AlterModelTable(
            name='sale',
            table='sale',
        ),
    ]
