# Generated by Django 3.2.4 on 2021-07-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_alter_sale_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='g_name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='unit',
        ),
    ]
