# Generated by Django 3.2.4 on 2021-07-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_auto_20210702_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='s_num',
            field=models.PositiveIntegerField(verbose_name='销售数量'),
        ),
    ]
