# Generated by Django 3.2.4 on 2021-07-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_alter_sale_s_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sp_id',
        ),
    ]
